USE [master]
GO

/****** Object:  Database [MOTOCLUBE]    Script Date: 30/04/2015 11:28:31 ******/
CREATE DATABASE [MOTOCLUBE]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MOTOCLUBE', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\MOTOCLUBE.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'MOTOCLUBE_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\MOTOCLUBE_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [MOTOCLUBE] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MOTOCLUBE].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MOTOCLUBE] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MOTOCLUBE] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MOTOCLUBE] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MOTOCLUBE] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MOTOCLUBE] SET ARITHABORT OFF 
GO

ALTER DATABASE [MOTOCLUBE] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MOTOCLUBE] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [MOTOCLUBE] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MOTOCLUBE] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MOTOCLUBE] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MOTOCLUBE] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MOTOCLUBE] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MOTOCLUBE] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MOTOCLUBE] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MOTOCLUBE] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MOTOCLUBE] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MOTOCLUBE] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MOTOCLUBE] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MOTOCLUBE] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MOTOCLUBE] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MOTOCLUBE] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MOTOCLUBE] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MOTOCLUBE] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MOTOCLUBE] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MOTOCLUBE] SET  MULTI_USER 
GO

ALTER DATABASE [MOTOCLUBE] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MOTOCLUBE] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MOTOCLUBE] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MOTOCLUBE] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [MOTOCLUBE] SET  READ_WRITE 
GO


